name: Publish image to GHCR

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14.17.3
  IMAGE: ghcr.io/shivjm/scratchpay-clinic-search

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d%H%M%S)"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.image }}
          cache-to: type=inline
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          tags: "${{ env.IMAGE }}:${{ steps.date.outputs.date }},${{ env.IMAGE }}:latest"
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
